import type { NextPage } from 'next'
import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { QuestionList } from '../components/QuestionList'

interface Question {
	id: number
	title: string
}

const Home: NextPage = () => {
	const [questions, setQuestions] = useState([
		{ id: 1, title: 'Question 1', },
		{ id: 2, title: 'Question 2', },
		{ id: 3, title: 'Question 3', },
	] as Question[])
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">Next.js!</a>
				</h1>
				<QuestionList questions={questions} setQuestions={setQuestions} />
			</main>
		</div>
	)
}

export default Home
